name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean package -DskipTests


  security-check:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    # --- Trivy ---
    - name: Install Trivy (Caching Enabled)
      run: |
        if ! command -v trivy &> /dev/null; then
          echo "Installing Trivy..."
          sudo apt-get update -y
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.49.1_Linux-64bit.deb -O trivy.deb
          sudo dpkg -i trivy.deb
        else
          echo "Trivy already installed, skipping."
        fi

    - name: Trivy FS Scan (Fast)
      run: trivy fs --scanners vuln,secret --format json -o fs-report.json .

    # --- GitLeaks ---
    - name: Install GitLeaks (Caching Enabled)
      run: |
        if ! command -v gitleaks &> /dev/null; then
          echo "Installing GitLeaks..."
          wget https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -O gitleaks
          sudo install -m 755 gitleaks /usr/local/bin/gitleaks
        else
          echo "GitLeaks already installed, skipping."
        fi

    - name: GitLeaks Code Scan
      run: gitleaks detect -r gitleaks-report.json -f json
